from enum import Enum

class MsgType(str, Enum):
    REGISTER = "REGISTER"

    CALL_REQUEST = "CALL_REQUEST"
    CALL_ACK = "CALL_ACK"
    CALL_BROADCAST = "CALL_BROADCAST"
    CALL_REPLY = "CALL_REPLY"
    CALL_REPLY_BROADCAST = "CALL_RESPONSE_BROADCAST"

    TOGGLE_AUDIO_REQUEST = "TOGGLE_AUDIO_REQUEST"
    TOGGLE_AUDIO_BROADCAST = "TOGGLE_AUDIO_BROADCAST"

    TOGGLE_VIDEO_REQUEST = "TOGGLE_VIDEO_REQUEST"
    TOGGLE_VIDEO_BROADCAST = "TOGGLE_VIDEO_BROADCAST"

    ONLINE_USERS_REQUEST = "ONLINE_USERS_REQUEST"
    ONLINE_USERS_RESPONSE = "ONLINE_USERS_RESPONSE"

    LEAVE_CALL_REQUEST = "LEAVE_CALL_REQUEST"
    LEAVE_CALL_RESPONSE = "LEAVE_CALL_RESPONSE"

class MsgCategory(str, Enum):
    request = "request"
    response = "response"
    broadcast = "broadcast"